# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:05nqFYK7e9lFE7Wu7uE7kox4oHWag+qhBg==,iv:c/H3AoN3dw2GVPxOOuIYan6ezFbMheNmEKvHXJH6ekc=,tag:iCYH82Ed0fOERx139BgRLA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:3drCzKavU+l91ADqUY4CgK5XDTHHu1FkVkAJt/N4l0uDhIp5+Q==,iv:QSCxZyJWsLAFeDY81cqguqwhDPnIRiUjdPz9fIsXyhs=,tag:THcPilCGaPZ3bmXm3rIP/Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:/5Ls2siwoLE4WgQm93H6Aw==,iv:zX99P36jjWAkwrm4VpLNqAjoTO81MM+OAGt1xUI0Mcc=,tag:UIpwZD1B2Tn/+UI+ltJsWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w5n9srawz0e4rrxtmm4fq9he9r7t5jy3w5jr7r40tz9ksy2txcssvlaw5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtS1hmRHhuK0RVNGlnV3Nr
            TW9EazAzVVlpbkhxdHBLZkNnYUJuejF1ZXhVClIxYUJCdG90R3g5YXMzQW1PQkFW
            MFZyRmRYbmQ3K3NiN2lPdTNxcnd1bjQKLS0tIDEyTUFlVTExUGpYazNneGp6QWhs
            QUFqNGJCV3RLY0gvU2M4Z3RnSHBsVWsKjj2RAE4La3bCl2Cs7ZgGbYwfW4xFbJqD
            GRd0htsapcYK4aZeQW5GDgwAq0tWiWCZ8MgasuKQo4rate8WYYwXgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-01T07:17:30Z"
    mac: ENC[AES256_GCM,data:/0ZMuJqY5a4sxixDXi3Cg46ntbKrArGMr3vbhaVn1OBaVrivj9/7G6XoZ9IeMHTOvh+rMfDBY+QwiOMEd65+On+UqGaAx6k2qhA5DIDbsPrFBIRT96ADMaIzlxan9+p/U48419GghUG6yP4kRmCQEXp0XwVIez2+hCX/4edEtMA=,iv:z9SFuLbUMZT7cKiD2hQNl96kmDFKyqvgJrfi8OxcoTw=,tag:Z3Ng6saG3RLwLdpTPOAqSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
