kind: Secret
ansible_user: ENC[AES256_GCM,data:pC88IDIs,iv:MbUY1WWINQW2a7X5cvjtkUM4XUlY0WzgmjRWkTANagw=,tag:dmSDDX3jfqRWCWdYWGjBUg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:3B2Fzagf,iv:Bgv4VhpbFRjxzjDqM6sgVyXI6j4zXXL/DsMu+jqNi8k=,tag:86M87wmaPhPCUKjopW6zrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w5n9srawz0e4rrxtmm4fq9he9r7t5jy3w5jr7r40tz9ksy2txcssvlaw5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYzR1T2YzNGxSVUxwQ3Vs
            dzVLbHI0a1JqeDFzeE1FRDhWUGh2ZFF3bVE0CkZYWkpUaGVYVlZubm1udXVLOTRR
            QW4yY1hGVTdFUVdGRXpBUmtxK0hEbFUKLS0tIEV5dEphWnErbnVDbnhPZFZ5cTRq
            M2I2TWpkaEx2RnBTSThBQ3VTejkxWmsKJJCQFgAR8Yo5w7ZGhVcmnQ0Dn7Kx9/RB
            mrgIXOugZIxbpYiE6xkyvOrqkvm5M4S7cAq0POANYOj5Rsx4yTXm6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-01T01:36:46Z"
    mac: ENC[AES256_GCM,data:H8j45wP0o1S5T3QgWmUQnh0elgZkuPyyW9UXrT5Hd0UEtw140flnURp5Don4M3DBTMvAF+MHoCSvBr4P1RRrkf5sLFKI0UTud9KdEcEDSX8m/vU7H0MgJVYyrcY30lRMufczOM8oAd/WePufDtxpczQC1LQPwZKybIm4Ht/7Dp4=,iv:n7KRLCT0OQi0wJ3P/Ryd6cIo7YWk0owvA+cVJIDbBro=,tag:FNwgKSINc7Orik3PSpTSMA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
