kind: Secret
ansible_user: ENC[AES256_GCM,data:8tnCQH1P,iv:VJiY2kHm3JRZOpS9ijiplo6tH+ndV64cxedGRCdDsxM=,tag:e1zBup2CqrAE/+LGMKw1wQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:1oNgOPht,iv:xjzmv5IkBItHufzn4RsOBzWAmM1aCp1Z7EQjCY6LhGU=,tag:MZIYgZFuyi+NZVzfE/qVXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w5n9srawz0e4rrxtmm4fq9he9r7t5jy3w5jr7r40tz9ksy2txcssvlaw5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpV2d5bS9UaWdQTktmdytX
            QUtkSXhkb01hV2drd0tjRHdhVTJqTmhRbkFFClh2Z1k4bzhXbVU4dWFRYnhnU1Uz
            blZ6dHpEVVJRMGNZdUI4cXdXRTBra0EKLS0tIEVWS2kva2xuU0FaWTM0V0dSL1Jr
            ZHc3REM4bXJJc1Q2WVorYjlwTVp3eE0KjpdIlarVrTxmEIkron2CrNeTVjWasEtM
            gz4UTHTovwVG9fHlLV7xlOMymsQ+IZgX+Ptyx6H7/q24fw4R1dgZow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-01T07:17:30Z"
    mac: ENC[AES256_GCM,data:ZA+N1V7hkmrIUYGtvAZO0XupkMSlvmxAFwUZAQHXeYc+aAhSGCJIATd8yuAT60m8ZVsatTgIEJfNlNbySQpJnHrsKmyojhVUgf8GVrQMLO0kkmo/n7Q3ZeKO7myyo7+4zicKpFO9MxfafeClSUUcvHygPIsAOzDihUeEvnneRD0=,iv:iOelg6UpjfGwEAbl2h8ZdtGYCNdwuCcx0raBOvilcns=,tag:JIrjy1NaDyan5jKCg5N0Ug==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
