# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:pkgRjoxDcYK3DI6hIlo48/GmgUAEP1gylyjX/rXOkZluLdO9qA==,iv:fsbwkOBv7Q8W1yqtKjUh9thfG5wtFUILXl9DAKxy6ak=,tag:v62GbOttTkP7ouJJ2oIFLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w5n9srawz0e4rrxtmm4fq9he9r7t5jy3w5jr7r40tz9ksy2txcssvlaw5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeUYwc1hNd01tdXQ1ZXJK
            ajdZRy82L3laU0VlOHgwTGhLeUp5aXdWUG1nCnFCaWdJOWpkVXBBbEk5cTVMVVQ5
            ZE4xb2hCQUJnQmpRVVRtYndyRVNOR3cKLS0tIHRaNnhxMGhnbWw3UDNaWW0yek4v
            MU56eWduejFtQVVud1p6ckNCUEFkK2MKhM2wzzDsbkeeWEeYnDy2EcOHOELCS02r
            3wUUc1yF7gGxHUUNhTY2Dspjn6GZ4I7179WEesMaK4ZwMQnwEnJ7Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-01T01:36:46Z"
    mac: ENC[AES256_GCM,data:AgXknvaQvG8iv+aeeHTYegA/ihFkpwQo4F2olY9s2C+ZggrLxkMeLDXqOGNRVwHakrYOvWqK/8zktDmT0dm1leMdnijXllXqbwAG6ks5+qyV9O0YaQy1H5N9ibtR4E95wfu1ZiApBPLE73sLs7HiOJ09KvLt1Y8VfzxAk/YPAkA=,iv:iVcP/piJdG/ZB7xrPSnA1njsCzKUu0eS3vmgn5r0eR4=,tag:iG6M845hxrrJ0UvhQN6cWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
